### ISSUE TITLE
Gracefully handle too many events during a given time period

### ISSUE THREAD

**Issue by kylecombes** [kylecombes/ultra-responsive-calendar#5]
What happens if:
* there are too many events on a day in the month view?
* there are too many events occurring simultaneously in a day column view?

**Comment by kylecombes** [comment]
Resolved for month view by a629cb4b44c388f96584e6ac3dce5e8bdad6a33e. Still need to address multi-day view.

**Comment by kylecombes** [comment]
This is what happens when there are too many events on the multi-day view:
![image](https://user-images.githubusercontent.com/3915596/38890571-cc85080c-424f-11e8-9a6e-ba6a84298313.png)

**Comment by kylecombes** [comment]
Addressed reasonably enough in 2eddf22d95c49f4278bed6038007d3d3a8feb770. Padding and border radius reduced and line-wrapping re-enabled.

**Comment by osteele** [comment]
This is much better but there's room for improvement. I recommend re-opening this but removing the “bug” label; or, creating another issue labeled “enhancement”.

Here are the week views for that day in ABE and Google Calendar, as of olinlibrary/abe-web#a433eae that is locked to this repo's #6ae1b6b.

## 3-Day View (ABE)

<img width="405" alt="screenshot of safari 5-10-18 7-40-50 am" src="https://user-images.githubusercontent.com/674/39868074-037184f2-5426-11e8-98e7-886e6078541a.png">

## Week View (ABE)

<img width="209" alt="screenshot of safari 5-10-18 7-41-01 am" src="https://user-images.githubusercontent.com/674/39868065-fb6e96be-5425-11e8-96df-5cef76395f13.png">

## Week View (Google Calendar)

<img width="171" alt="screenshot of safari 5-10-18 7-46-47 am" src="https://user-images.githubusercontent.com/674/39868203-86a5656e-5426-11e8-85ff-a73d64707daf.png">
